###
GET http://localhost:3003/student/zé

###
POST http://localhost:3003/class
Content-Type: application/json

{
   "name":"STEVZINHO",
   "module":"0"
}

###
POST http://localhost:3003/instructor
Content-Type: application/json

{
    "name":"Iago",
    "email": "iago@labenu.com.br",
    "birth_date": "1990-05-17",
    "class_id": "27d5835d-1ebd-45f6-9cc6-8201687bdae5",
    "specialty": "04"
}

###
POST http://localhost:3003/student
Content-Type: application/json

{
    "name":"zé",
    "email": "zezin@linda.com.br",
    "birth_date": "2000-09-22",
    "class_id": "27d5835d-1ebd-45f6-9cc6-8201687bdae5",
    "hobby": "Jogar Mine"
}

###
GET http://localhost:3003/instructors


###
GET http://localhost:3003/class