###
GET http://localhost:3003/student/zé

###
GET http://localhost:3003/instructors

###
GET http://localhost:3003/class

###
POST http://localhost:3003/class
Content-Type: application/json

{
   "name":"STEVesss",
   "module":"1"
}

###
POST http://localhost:3003/instructor
Content-Type: application/json

{
    "name":"jessica",
    "email": "jessica2@labenu.com.br",
    "birth_date": "1998-05-17",
    "class_id": "27d5835d-1ebd-45f6-9cc6-8201687bdae5",
    "specialty": "02"
}

###
POST http://localhost:3003/student
Content-Type: application/json

{
    "name":"PedroScooby",
    "email": "pedroscooby@bbb.com.br",
    "birth_date": "2003-07-22",
    "class_id": "27d5835d-1ebd-45f6-9cc6-8201687bdae5",
    "hobby": "Jogar Mine"
}




//alterar turma do  instructor
###
PUT http://localhost:3003/instructor/f62bf662-892f-458c-ab12-6ad8dcb50b86
Content-Type: application/json


{
 "class_id":"be8338c6-dfa2-40d9-af83-8474137c18a7"  
}

//alterar modulo da turma
###
PUT http://localhost:3003/class/d9d00231-6310-49fa-a05a-510f874dae21
Content-Type: application/json


{
 "module": 5
}





//alterar turma do aluno 
###
PUT http://localhost:3003/student/ff1576e9-4aa2-499b-9e06-47cb081a4d26
Content-Type: application/json

{
 "class_id":"be8338c6-dfa2-40d9-af83-8474137c18a7"  
}




